// Fichier généré automatiquement contenant les catégories d'exercices.

const exercicesCategories = {
    "Endurance Musculaire": [
        "Bench Press - Sans poids",
        "Crunches - Avec Poids de cheville",
        "Crunches - Obliques",
        "Crunches - Sans Poids",
        "Deadlift - Sans poids",
        "Dips sur banc - Avec poids cheville",
        "Dips sur banc - Classique",
        "Dips sur banc - Incliné",
        "Dips sur banc - Unilatéral",
        "Développé décliné - Sans poids",
        "Développé incliné - Sans poids",
        "Fentes bulgares - Sans poids",
        "Hip Thrusts - Sans poids",
        "Leg Raises - Avec Poids Cheville",
        "Leg Raises - Classique",
        "Leg Raises - Latéraux",
        "Leg Raises - Sur Banc",
        "Lunges - Arrière",
        "Lunges - Classique",
        "Lunges - Sans poids",
        "Marche avec Voile d’Ombre - Lourd",
        "Marche avec Voile d’Ombre - Léger",
        "Marche avec Voile d’Ombre - Réaliste",
        "Marche du fermier - Avec barre trapèze",
        "Marche du fermier - Avec haltères",
        "Marche du fermier - Classique",
        "Marche du fermier - Unilatéral",
        "Pelleter la neige",
        "Plank - Avec Pieds sur Banc",
        "Plank - Avec Poids Cheville",
        "Plank - Classique",
        "Plantarflexion - Classique",
        "Plantarflexion - Sans poids",
        "Plantarflexion - Sur banc",
        "Pompes - Avec pieds sur banc",
        "Pompes - Avec poids cheville",
        "Pompes - Classique",
        "Pull-overs - Sans poids",
        "Russian Twists - Classique",
        "Russian Twists - Sans Poids",
        "Russian Twists - Sur Banc",
        "Sit-ups - Avec Poids Cheville",
        "Sit-ups - Sans Poids",
        "Squats - Sans poids",
        "Squats avant - Sans poids",
        "Step-ups - Avec banc",
        "Step-ups - Classique",
        "Step-ups - Sans poids"
    ],
    "Hypertrophie": [
        "Arnold Press - Assis",
        "Arnold Press - Avec barre",
        "Arnold Press - Avec haltères",
        "Arnold Press - Classique",
        "Bench Press - Avec haltères",
        "Bent-over Rows - Avec haltères",
        "Bent-over Rows - Unilatéral",
        "Crunches - Avec Haltère",
        "Curl Biceps - Avec barre olympique",
        "Deadlift - Avec haltères",
        "Développé décliné - Avec haltères",
        "Développé incliné - Avec haltères",
        "Fentes bulgares - Avec banc",
        "Fentes bulgares - Avec haltères",
        "Fentes bulgares - Classique",
        "Hip Thrusts - Avec haltères",
        "Hip Thrusts - Classique",
        "Lunges - Avec haltères",
        "Overhead Press - Avec haltères",
        "Plantarflexion - Avec haltères",
        "Pull-overs - Avec haltère",
        "Pull-overs - Classique",
        "Pull-overs - Sur banc",
        "Russian Twists - Avec Haltère",
        "Shrugs - Avec haltères",
        "Shrugs - Classique",
        "Shrugs - Unilatéral",
        "Sit-ups - Avec Haltère",
        "Sit-ups - Inclinés",
        "Soulevé de terre - Avec haltères",
        "Soulevé de terre - Unilatéral",
        "Squats - Avec haltères",
        "Squats avant - Avec haltères",
        "Step-ups - Avec haltères",
        "Écartés - Avec haltères",
        "Écartés - Classique",
        "Écartés - Incliné",
        "Écartés - Sur banc"
    ],
    "Puissance": [
        "Boxing Punches - Avec poids poignet",
        "Boxing Punches - Classique",
        "Boxing Punches - Sur sac de frappe",
        "Coup de frappe - Éclat de Jeter Lourd",
        "Coup de taille - Lames Jumelles Lourd",
        "Coups de poing/pied/genou",
        "Donkey Kicks - Explosifs",
        "Estoc puissant - Ombre de la Frappe Lourd",
        "Plank - Dynamique",
        "Plank Punches - Avec poids poignet",
        "Plank Punches - Classique",
        "Plank Punches - Latéraux",
        "Plank Punches - Sur banc",
        "Pompes - Explosives",
        "Poussée de bouclier - Rempart de Thornval Lourd",
        "Sauts sur banc",
        "Shadow Boxing",
        "Sprints sur place",
        "Voile d’Ombre - Lourd"
    ],
    "Force Maximale": [
        "Bench Press - Classique",
        "Bench Press - Incliné",
        "Bent-over Rows - Avec barre trapèze",
        "Bent-over Rows - Classique",
        "Coup de taille - Tranche-Tête Lourd",
        "Coup de taille - Tranche-Tête Maudite Léger",
        "Coup de taille - Tranche-Tête Maudite Réaliste",
        "Coup de taille - Tranche-Tête Ultra-lourd",
        "Deadlift - Classique",
        "Deadlift - Roumain",
        "Développé décliné - Avec barre olympique",
        "Développé décliné - Classique",
        "Développé incliné - Avec barre courte",
        "Développé incliné - Classique",
        "Hip Thrusts - Avec barre olympique",
        "Overhead Press - Assis",
        "Overhead Press - Avec barre olympique",
        "Overhead Press - Classique",
        "Shrugs - Avec barre olympique",
        "Soulevé de terre - Avec barre trapèze",
        "Soulevé de terre - Roumain",
        "Squats - Classique",
        "Squats - Profond",
        "Squats avant - Avec barre olympique",
        "Squats avant - Classique"
    ],
    "Technique": [
        "Boxing Punches - Lents",
        "Clamshells - Avec poids cheville",
        "Clamshells - Avec résistance",
        "Clamshells - Classique",
        "Clamshells - Sur banc",
        "Concentration Curls - Avec haltère",
        "Concentration Curls - Avec poids poignet",
        "Concentration Curls - Classique",
        "Concentration Curls - Debout",
        "Coup de frappe - Éclat de Jeter Léger",
        "Coup de frappe - Éclat de Jeter Réaliste",
        "Coup de taille - Lames Jumelles Léger",
        "Coup de taille - Lames Jumelles Réaliste",
        "Curl Biceps - Avec haltères",
        "Curl Biceps - Classique",
        "Curl Biceps - Incliné",
        "Donkey Kicks - Avec banc",
        "Donkey Kicks - Avec poids cheville",
        "Donkey Kicks - Classique",
        "Estoc contrôlé - Ombre de la Frappe Réaliste",
        "Estoc rapide - Ombre de la Frappe Léger",
        "Extension triceps - Assis",
        "Extension triceps - Au-dessus",
        "Extension triceps - Avec barre",
        "Extension triceps - Avec haltère",
        "Face Pulls - Avec barre",
        "Face Pulls - Avec haltères",
        "Face Pulls - Improvisé",
        "Face Pulls - Sur banc",
        "Frappe dynamique - Voile d’Ombre Léger",
        "Front Raises - Assis",
        "Front Raises - Avec barre courte",
        "Front Raises - Avec haltères",
        "Front Raises - Classique",
        "Hammer Curls - Assis",
        "Hammer Curls - Avec haltères",
        "Hammer Curls - Classique",
        "Hammer Curls - Incliné",
        "Kick-back - Avec poids cheville",
        "Kick-back - Classique",
        "Kick-back - Latéral",
        "Kick-back - Sur banc",
        "Lateral Raises - Assis",
        "Lateral Raises - Avec haltères",
        "Lateral Raises - Avec poids poignet",
        "Lateral Raises - Classique",
        "Poussée de bouclier - Rempart de Thornval Léger",
        "Poussée de bouclier - Rempart de Thornval Réaliste",
        "Skull Crushers - Avec barre courte",
        "Skull Crushers - Avec haltères",
        "Skull Crushers - Classique",
        "Skull Crushers - Sur banc",
        "Voile d’Ombre - Réaliste"
    ],
    "Conditionnement Cardiovasculaire": [
        "Entraînement par intervalles",
        "Marche",
        "Randonnée",
        "Raquettes à neige",
        "Saut à la corde - Boxe",
        "Saut à la corde - Lesté",
        "Saut à la corde - Lesté d'intérieur",
        "Stepper",
        "Vélo de randonnée",
        "Vélo elliptique",
        "Vélo urbain"
    ]
};
